import type {Metadata} from "next";
import "./globals.css";
import AppProvider from "@/providers/app-provider";
import {Toaster} from "@/components/ui/toaster";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      <AppProvider>
        <div>
          {children}
          {/*<BottomNavigation />*/}
        </div>
        <Toaster />
        {/*<MainFooter/>*/}
      </AppProvider>
      </body>
    </html>
  );
}
